APP_ENV=local
APP_DEBUG=true
APP_URL=http://localhost:__WORKTREE_PORT__

DB_CONNECTION=pgsql
DB_HOST=infra-postgres
DB_PORT=5432
DB_DATABASE=__WORKTREE_DB__
DB_USERNAME=__WORKTREE_DB_USER__
DB_PASSWORD=__WORKTREE_DB_PASSWORD__

REDIS_HOST=infra-redis
REDIS_PORT=6379
CACHE_PREFIX=__WORKTREE_REDIS_PREFIX__

MAIL_MAILER=smtp
MAIL_HOST=infra-mailpit
MAIL_PORT=1025
