# __PROJECT_NAME__ — DevHub worktree hub

This folder is a DevHub-managed worktree hub for the `__PROJECT_NAME__`
project (stack: `__PROJECT_STACK__`). Code is never edited at this root:
every branch lives in its own Git worktree under `worktrees/`, served on its
own port with its own PostgreSQL database on the shared dev infra
(`dev-shared-net`).

## Layout

```text
repo.git/            bare Git repository (single source of truth)
worktrees/<slug>/    one checkout per branch — always work inside one of these
.claude/             agents, skills and permissions for this hub (generated)
CLAUDE.md, AGENTS.md this guide (generated by devhub project init/adopt)
```

## Rules for AI agents and terminals

1. **One terminal / one agent = one worktree.** Never run two parallel
   sessions in the same worktree. To work on a branch, claim or create its
   worktree first:

   ```bash
   devhub wt add __PROJECT_NAME__ <branch> --json
   ```

   Exit 0 = created, exit 3 = already registered (the JSON entry is printed
   either way). Then `cd` into the returned `.path`
   (`worktrees/<slug>/`) and do all work from there.
2. Before starting, check what already exists:
   `devhub wt list __PROJECT_NAME__ --json` and
   `devhub wt status __PROJECT_NAME__ --json`.
3. Serve all registered worktrees with `devhub runtime __PROJECT_NAME__`.
   Each worktree answers on its own `http://localhost:<port>`
   (range __PROJECT_PORT_START__-__PROJECT_PORT_END__); the dashboard lists
   them on http://localhost:__PROJECT_RUNTIME_PORT__.
4. Each worktree has its own env file and its own database/user on
   `infra-postgres`. Never point two worktrees at the same database, and
   never copy an env file from one worktree to another without fixing
   `DATABASE_URL`.
   In multi-app projects, `wt add --json` also returns an `apps` map (one
   port per app); cross-app URLs are injected into each app's env file as
   `DEVHUB_<APP>_URL` (plus `API_URL`/`NEXT_PUBLIC_API_URL` when an app is
   named `api`) — never hardcode a peer app port.
5. When a branch is merged or abandoned:
   `devhub wt rm __PROJECT_NAME__ <slug>` (exit 5 = uncommitted changes;
   ask the human before retrying with `--force`).
6. Never delete `repo.git`, never commit from this root, and never edit
   files outside the worktree you claimed.
7. Verify inside the worktree with the project's own checks (lint,
   type-check, tests) before reporting work as done, and check the served
   app on its worktree port when the change has a runtime surface.

## Orchestration (/orchestrate, /orchestrate-fast)

This hub ships two project skills and the agents they use
(`.claude/agents/`): `implementer`, `implementer-ui`, `implementer-backend`,
`implementer-tests` (write lanes) and `security-review`, `perf`
(read-only reviewers).

- `/orchestrate` — supervised cycle: plan → one implementation worktree →
  parallel review → human gate.
- `/orchestrate-fast` — round-based fan-out: **one implementation lane = one
  worktree = one branch**, consolidated by the lead.

Hard limits (always):
- The lead (this session, at the hub root) owns decomposition, worktree
  creation, merges and the final answer. Subagents never run
  `devhub wt add/rm`, never spawn other agents, never touch `repo.git` or a
  worktree they don't own.
- Max 4 implementation lanes; 2 by default.
- Never parallelize migrations, auth/security-sensitive code, billing, or a
  shared contract change: the lead serializes those first.
- Never push and never delete branches without explicit user approval.
- Stop every spawned teammate/background task as soon as its result is
  consolidated; leave nothing running when the work is delivered.
- End every delivered feature with its test URLs (worktree ports from
  `devhub wt status __PROJECT_NAME__ --json`), verified reachable first.

## Merge & ship (after the feature is validated)

Merges into the base branch happen in the worktree that has it checked out
(`worktrees/main/`), never at the hub root or in `repo.git`.

- **PR path (preferred when a remote exists):** from the feature worktree,
  `git push -u origin <branch>` then `gh pr create --base main` — push only
  with explicit user approval. After the PR merges: `cd worktrees/main &&
  git pull`, then `devhub wt rm __PROJECT_NAME__ <slug>` and delete the
  local branch.
- **Local path:** `cd worktrees/main && git merge <branch>`, re-run the
  checks there, then `devhub wt rm __PROJECT_NAME__ <slug>`.

`main` keeps running on its port through the merge (hot reload) — verify the
merged result live before cleaning up.
