# __PROJECT_NAME__ — DevHub worktree hub shortcuts (generated by devhub)
PROJECT := __PROJECT_NAME__
BASE ?= main

.PHONY: help run stop status ls urls add rm logs pull-main pr

help:
	@echo "Targets ($(PROJECT)):"
	@echo "  make run                           Start the runtime (serves every worktree)"
	@echo "  make stop                          Stop the runtime"
	@echo "  make status                        Worktree http/db status"
	@echo "  make ls                            List worktrees"
	@echo "  make urls                          Test URLs per worktree (all apps)"
	@echo "  make add BRANCH=feat/x [BASE=main] Create/register a worktree"
	@echo "  make rm SLUG=feat-x                Remove a worktree (refuses unmerged work)"
	@echo "  make logs                          Follow runtime logs"
	@echo "  make pull-main                     Update the main worktree after a merge"
	@echo "  make pr BRANCH=feat/x [BASE=main]  Push the branch and open a PR (gh)"

run:
	@devhub runtime $(PROJECT)

stop:
	@devhub down-runtime $(PROJECT)

status:
	@devhub wt status $(PROJECT)

ls:
	@devhub wt list $(PROJECT)

urls:
	@devhub wt list $(PROJECT) --json | jq -r '.worktrees[] | .slug + ":\t" + (if .apps then ([.apps | to_entries[] | .key + "=http://localhost:" + (.value|tostring)] | join("  ")) else .url end)'

add:
	@test -n "$(BRANCH)" || { echo "Usage: make add BRANCH=feat/x [BASE=main]"; exit 1; }
	@devhub wt add $(PROJECT) $(BRANCH) $(BASE)

rm:
	@test -n "$(SLUG)" || { echo "Usage: make rm SLUG=feat-x"; exit 1; }
	@devhub wt rm $(PROJECT) $(SLUG)

logs:
	@docker logs -f $(PROJECT)-runtime

pull-main:
	@git -C worktrees/main pull --ff-only

pr:
	@test -n "$(BRANCH)" || { echo "Usage: make pr BRANCH=feat/x [BASE=main]"; exit 1; }
	@git -C "worktrees/$(subst /,-,$(BRANCH))" push -u origin "$(BRANCH)"
	@gh pr create --base "$(BASE)" --head "$(BRANCH)" --fill || gh pr view "$(BRANCH)" --web
